---
# handlers file for tomcat10
- name: Reload and Restart systemd daemon
  ansible.builtin.systemd:
    name: "{{ user_name }}"
    state: restarted   
    enabled: yes      
    daemon_reload: true